---
swagger: '2.0'
info:
  title: Cats spec
  version: 0.0.1
basePath: /api
paths:
  /cat/{id}:
    get:
      tags:
        - cats
      operationId: getCat
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Cat'
definitions:
  Cat:
    type: object
    properties:
      value:
        type: string
