---
swagger: '2.0'
info:
  title: Main spec
  version: 0.0.1
x-package-name: com.github.slamdev.sample.service2.api
x-api-name-prefix: SampleService2
x-path-variable-name: sample.service2.url
basePath: /api
paths:
  /keys/{id}:
    get:
      operationId: getKeys
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Key'
    post:
      operationId: createKey
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: key
          in: body
          required: true
          schema:
            $ref: '#/definitions/Key'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Key'
definitions:
  Key:
    type: object
    properties:
      name:
        $ref: '#/definitions/Name'
      value:
        type: string
      created:
        type: string
        format: date-time
      num:
        type: number
      uuid:
        type: string
        format: uuid
      eventType:
        type: string
        description: Event Type
        enum:
          - A
          - B
          - C
  Name:
    type: string
    enum:
      - FIRST
      - LAST
